name: poll_power_openapi_generated
description: Poll power openapi code genereted.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.8.1
  openapi_base: ^1.3.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  injectable_generator: ^2.6.0
  openapi_code_builder: ^1.3.0

scripts:
  build: "dart run build_runner build --delete-conflicting-outputs"
  watch: "dart run build_runner watch"
  push: "git add . && git commit -m 'openapi generated' && git push"